/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseImage: typeof import('./components/global/BaseImage/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanSkeletonAvatar: typeof import('vant/es')['SkeletonAvatar']
    VanSkeletonParagraph: typeof import('vant/es')['SkeletonParagraph']
  }
}
